TOPLEVEL_LANG = verilog
SIM ?= verilator
# VERILOG_SOURCES = $(PWD)/../rtl/blink.v
VERILOG_SOURCES = $(PWD)/../rtl/prbs7.v
# TOPLEVEL = blink
TOPLEVEL = prbs7
# MODULE = test_blink
MODULE = test_prbs7
include $(shell cocotb-config --makefiles)/Makefile.sim